# Generated by Django 4.0 on 2022-03-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailconfirmationtoken'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailconfirmationtoken',
            table='tokens',
        ),
    ]
