# Generated by Django 4.0 on 2022-03-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0004_alter_emailconfirmationtoken_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailConfirmationToken',
            new_name='Token',
        ),
    ]
