# Generated by Django 4.0 on 2022-01-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_tags_article_tags_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags_old',
            field=models.ManyToManyField(related_name='articles_old', through='webapp.ArticleTag', to='webapp.Tag'),
        ),
    ]
