# Generated by Django 4.0 on 2022-01-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20220113_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags_old',
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
