# Generated by Django 4.0 on 2022-01-17 15:11

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_article_tags_old_delete_articletag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='Unknown', max_length=200, validators=[webapp.validators.MinLengthValidator(5)], verbose_name='Автор'),
        ),
    ]
