# Generated by Django 4.0 on 2022-01-26 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='webapp.status', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='webapp.type', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
