# Generated by Django 4.0 on 2022-01-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_article_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='types',
            field=models.ManyToManyField(related_name='articles', to='webapp.Type'),
        ),
    ]
