# Generated by Django 4.0 on 2022-03-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
