# Generated by Django 3.2.12 on 2022-04-13 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_review_is_moderated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Контент'),
        ),
    ]
