# Generated by Django 4.0 on 2022-01-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_type_value_transfer_for_article_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type_old',
        ),
    ]
